fun main(args: Array<String>) {

    println(
        solution(
            intArrayOf(
                9,
                3,
                9,
                3,
                9,
                7,
                9,
                9,
                3,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                9,
                3,
                9,
                7,
                1,
                9,
                3,
                9,
                7,
                9
            )
        )
    )
//    println(solution(32))

}

fun solution(A: IntArray): Int {
    val hashMap = HashMap<Int, Int>()

    for (i in A) {
        hashMap[i] = hashMap.getOrDefault(i, 0) + 1
    }

    for (key in hashMap.keys) {
        val occurrences: Int? = hashMap[key]
        if (occurrences!! % 2 != 0) return key
    }

    throw RuntimeException("리턴할 수 없는 경우도 들어오기 때문에 에러를 던져주자");
}

fun solution() {

}
